/*
 * PnlFondo.java
 *
 * Created on 19 de julio de 2007, 07:56 PM
 */

package ar.edu.frc.utn.avads.igu;

import ar.edu.frc.utn.avads.util.AvadsUtil;
import ar.edu.frc.utn.avads.util.PropertiesClientUtil;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author  Jorge
 */
public class PnlFondoJDialog extends javax.swing.JPanel {        
    
    private String estiloVentana;
    /** Creates new form PnlFondo */
    public PnlFondoJDialog(String estiloVentana) {
        initComponents();
        
        this.estiloVentana = estiloVentana;
    }
    
    @Override
    public void paintComponent(Graphics g){
        
        Dimension tamanio = getSize();              
        ImageIcon imagenFondo = null;

        String[] estilosVentana = PropertiesClientUtil.getProperty("igu.configuracion.estilos.ventana").split(",");
        
        for(String estG : estilosVentana)
        {
            String estGAux = PropertiesClientUtil.getProperty("igu.configuracion.estilo."+estG);
            estGAux = estGAux.substring(estGAux.lastIndexOf(".")+1);
            if(estiloVentana.compareTo(estGAux) == 0)
            {
                imagenFondo = AvadsUtil.getImageIconByPath(PropertiesClientUtil.getProperty("igu.jdiFondo.imagen.estilo."+estGAux));
                break;
            }
        }
        
        g.drawImage(imagenFondo.getImage(), 0, 0, 
                tamanio.width, tamanio.height, null);
        setOpaque(false);
        
        super.paintComponent(g);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
