/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.edu.frc.utn.avads.igu;

import ar.edu.frc.utn.avads.main.AvadsMain;
import ar.edu.frc.utn.avads.model.AnalisisArchivo;
import ar.edu.frc.utn.avads.util.AvadsUtil;
import java.awt.Image;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ecarballo
 */
public class VentanaEstadoArchivos extends javax.swing.JDialog {

    /**
     * Creates new form VentanaEstadoArchivos
     */
    private java.awt.Frame padre;
    private static DefaultTableModel estadoArchivosModel = new DefaultTableModel();
    
    public VentanaEstadoArchivos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        padre = parent;
        Image icono = AvadsUtil.getImageByPath(AvadsMain.propC.getProperty("icono.system.image"));
        this.setIconImage(icono);
        
        this.setTitle(AvadsMain.propC.getProperty("igu.estadoArchivos.title"));
        
        jPanelEstadoArchivos.setBorder(javax.swing.BorderFactory.createTitledBorder(AvadsMain.propC.getProperty("igu.estadoArchivos.panelEstadoArchivos.title")));
        jPanelFiltroEstadoArchivos.setBorder(javax.swing.BorderFactory.createTitledBorder(AvadsMain.propC.getProperty("igu.estadoArchivos.panelFiltroEstadoArchivos.title")));
        
        jLabelFecha.setText(AvadsMain.propC.getProperty("igu.estadoArchivos.fecha"));
        jButtonVer.setText(AvadsMain.propC.getProperty("igu.estadoArchivos.boton.ver"));
        

        jTableEstadoArchivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                AvadsMain.propC.getProperty("igu.estadoArchivos.columna.fecha"), AvadsMain.propC.getProperty("igu.estadoArchivos.columna.idProceso"), AvadsMain.propC.getProperty("igu.estadoArchivos.columna.archivosEnProceso"), AvadsMain.propC.getProperty("igu.estadoArchivos.columna.estado")
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        }); 
        
        estadoArchivosModel = (DefaultTableModel) jTableEstadoArchivos.getModel();  
        jTableEstadoArchivos.setSelectionMode(jTableEstadoArchivos.getSelectionModel().SINGLE_SELECTION);
        
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        
        jTableEstadoArchivos.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTableEstadoArchivos.getColumnModel().getColumn(1).setPreferredWidth(60);
        jTableEstadoArchivos.getColumnModel().getColumn(2).setPreferredWidth(150);        
        jTableEstadoArchivos.getColumnModel().getColumn(3).setPreferredWidth(90);

        
        jTableEstadoArchivos.getColumnModel().getColumn(0).setCellRenderer(tcr);
        jTableEstadoArchivos.getColumnModel().getColumn(1).setCellRenderer(tcr); 
        jTableEstadoArchivos.getColumnModel().getColumn(2).setCellRenderer(tcr);
        jTableEstadoArchivos.getColumnModel().getColumn(3).setCellRenderer(tcr);         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFiltroEstadoArchivos = new javax.swing.JPanel();
        jLabelFecha = new javax.swing.JLabel();
        jXDatePickerFechaEjecucion = new org.jdesktop.swingx.JXDatePicker();
        jButtonVer = new javax.swing.JButton();
        jPanelEstadoArchivos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEstadoArchivos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelFiltroEstadoArchivos.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtro Estado Archivos"));

        jLabelFecha.setText("Fecha:");

        jButtonVer.setText("Ver");

        javax.swing.GroupLayout jPanelFiltroEstadoArchivosLayout = new javax.swing.GroupLayout(jPanelFiltroEstadoArchivos);
        jPanelFiltroEstadoArchivos.setLayout(jPanelFiltroEstadoArchivosLayout);
        jPanelFiltroEstadoArchivosLayout.setHorizontalGroup(
            jPanelFiltroEstadoArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltroEstadoArchivosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXDatePickerFechaEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFiltroEstadoArchivosLayout.setVerticalGroup(
            jPanelFiltroEstadoArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltroEstadoArchivosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFiltroEstadoArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha)
                    .addComponent(jXDatePickerFechaEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVer))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanelEstadoArchivos.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado Archivos"));

        jTableEstadoArchivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "ID Proceso", "Archivos en Proceso", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableEstadoArchivos);

        javax.swing.GroupLayout jPanelEstadoArchivosLayout = new javax.swing.GroupLayout(jPanelEstadoArchivos);
        jPanelEstadoArchivos.setLayout(jPanelEstadoArchivosLayout);
        jPanelEstadoArchivosLayout.setHorizontalGroup(
            jPanelEstadoArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstadoArchivosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelEstadoArchivosLayout.setVerticalGroup(
            jPanelEstadoArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelEstadoArchivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelFiltroEstadoArchivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFiltroEstadoArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelEstadoArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void agregarAnalisisArchivo(AnalisisArchivo anA)
    {        
        if (estadoArchivosModel != null)
        {
            Object[] datosAnalisisArchivo = new Object[4];
            
            datosAnalisisArchivo[0] = new String(AvadsUtil.getDate(anA.getFechaEnvio())+" "+AvadsUtil.getHour(anA.getFechaEnvio()));
            datosAnalisisArchivo[1] = new Long(anA.getIdProceso());
            datosAnalisisArchivo[2] = new String(anA.getArchivo());            
            datosAnalisisArchivo[3] = new String(anA.getEstado());

            estadoArchivosModel.addRow(datosAnalisisArchivo);
        }
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVer;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JPanel jPanelEstadoArchivos;
    private javax.swing.JPanel jPanelFiltroEstadoArchivos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEstadoArchivos;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerFechaEjecucion;
    // End of variables declaration//GEN-END:variables
}
