/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.edu.frc.utn.avads.igu;

import ar.edu.frc.utn.avads.util.AvadsUtil;
import ar.edu.frc.utn.avads.util.PropertiesClientUtil;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.JOptionPane;

/**
 *
 * @author zurdoju
 */
public class VentanaConfiguracion extends javax.swing.JDialog {

    /**
     * Creates new form VentanaConfiguracion
     */
    
    private java.awt.Frame padre;
    public VentanaConfiguracion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        padre = parent;
        Image icono = AvadsUtil.getImageByPath(PropertiesClientUtil.getProperty("icono.system.image"));
        this.setIconImage(icono);
        
        this.setTitle(PropertiesClientUtil.getProperty("igu.configuracion.title")); 
        
        jPanelSeleccionEstilio.setBorder(javax.swing.BorderFactory.createTitledBorder(PropertiesClientUtil.getProperty("igu.configuracion.panelEstilos.title")));
        
        jButtonGuardar.setIcon(AvadsUtil.getImageIconByPath(PropertiesClientUtil.getProperty("igu.configuracion.imagen.boton.guardar")));
        jButtonGuardar.setToolTipText(PropertiesClientUtil.getProperty("igu.configuracion.boton.guardar"));
        jButtonCancelar.setIcon(AvadsUtil.getImageIconByPath(PropertiesClientUtil.getProperty("igu.configuracion.imagen.boton.cancelar")));
        jButtonCancelar.setToolTipText(PropertiesClientUtil.getProperty("igu.configuracion.boton.cancelar"));
        
        String[] estilosVentana = PropertiesClientUtil.getProperty("igu.configuracion.estilos.ventana").split(",");
        for(String estilo : estilosVentana) jComboBoxEstiloVentana.addItem(estilo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSeleccionEstilio = new javax.swing.JPanel();
        jComboBoxEstiloVentana = new javax.swing.JComboBox<>();
        jButtonVer = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanelSeleccionEstilio.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccion Estilo Ventana"));

        jButtonVer.setText("Ver");
        jButtonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSeleccionEstilioLayout = new javax.swing.GroupLayout(jPanelSeleccionEstilio);
        jPanelSeleccionEstilio.setLayout(jPanelSeleccionEstilioLayout);
        jPanelSeleccionEstilioLayout.setHorizontalGroup(
            jPanelSeleccionEstilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeleccionEstilioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxEstiloVentana, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelSeleccionEstilioLayout.setVerticalGroup(
            jPanelSeleccionEstilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeleccionEstilioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSeleccionEstilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEstiloVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSeleccionEstilio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 296, Short.MAX_VALUE)
                        .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSeleccionEstilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerActionPerformed
        String estiloSel = String.valueOf(jComboBoxEstiloVentana.getSelectedItem());
        if(estiloSel.compareTo("WindowsLookAndFeel") == 0)
        {
            mostrarMensaje(PropertiesClientUtil.getProperty("igu.configuracion.estilo.mensaje"));
            return;
        }
        else
        {
            int ancho = 1060;
            int alto = 680;
            JDiFondo jdiFondo = new JDiFondo(padre, true, estiloSel);
            jdiFondo.setSize(ancho, alto);
            jdiFondo.setPreferredSize(new Dimension(ancho, alto));
            jdiFondo.configurar(estiloSel);
            jdiFondo.setLocationRelativeTo(null);
            jdiFondo.setVisible(true);
            jdiFondo.requestFocus();
        }
    }//GEN-LAST:event_jButtonVerActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        PropertiesClientUtil.setProperty("estilo.ventana", PropertiesClientUtil.getProperty("igu.configuracion.estilo."+String.valueOf(jComboBoxEstiloVentana.getSelectedItem())));        
        mostrarMensaje(PropertiesClientUtil.getProperty("igu.configuracion.mensaje.guardar.ok"));        
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void mostrarMensaje(String mensaje)
    {
        JOptionPane.showMessageDialog(this, mensaje, PropertiesClientUtil.getProperty("ventana.dialogo.atencion"), JOptionPane.INFORMATION_MESSAGE);
    }    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonVer;
    private javax.swing.JComboBox<String> jComboBoxEstiloVentana;
    private javax.swing.JPanel jPanelSeleccionEstilio;
    // End of variables declaration//GEN-END:variables
}
