/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.edu.frc.utn.avads.igu;

import ar.edu.frc.utn.avads.main.AvadsMain;
import ar.edu.frc.utn.avads.util.AvadsUtil;
import java.awt.Image;
import javax.swing.JOptionPane;

/**
 *
 * @author zurdoju
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
        
    public VentanaPrincipal() {
        initComponents();
        
        Image icono = AvadsUtil.getImageByPath(AvadsMain.propC.getProperty("icono.system.image"));
        this.setIconImage(icono);
        
        this.setTitle(AvadsMain.propC.getProperty("igu.principal.title"));
        
        Image imagen = AvadsUtil.getImageByPath(AvadsMain.propC.getProperty("igu.principal.imagen.fondo"));        
        this.getContentPane().add(new PanelFondo(imagen), "Center");
        this.setExtendedState(MAXIMIZED_BOTH);
        
        jMenuAcciones.setText(AvadsMain.propC.getProperty("igu.menu.acciones"));      
        jMenuAyuda.setText(AvadsMain.propC.getProperty("igu.menu.ayuda"));
        jMenuConfiguracion.setText(AvadsMain.propC.getProperty("igu.menu.configuracion"));
        jMenuItemExaminarArchivo.setText(AvadsMain.propC.getProperty("igu.menu.acciones.examinarArchivo"));
        jMenuItemSalir.setText(AvadsMain.propC.getProperty("igu.menu.acciones.salir"));
        jMenuItemAyuda.setText(AvadsMain.propC.getProperty("igu.menu.ayuda.ayuda"));
        jMenuItemAcerca.setText(AvadsMain.propC.getProperty("igu.menu.ayuda.acercaAVADS"));
        jMenuItemConfiguracion.setText(AvadsMain.propC.getProperty("igu.menu.configuracion.configuracion"));
        jMenuItemEstadoArchivos.setText(AvadsMain.propC.getProperty("igu.menu.acciones.estadoArchivos"));
        
        jMenuItemAcerca.setIcon(AvadsUtil.getImageIconByPath(AvadsMain.propC.getProperty("igu.principal.imagen.acerca")));
        jMenuItemSalir.setIcon(AvadsUtil.getImageIconByPath(AvadsMain.propC.getProperty("igu.principal.imagen.salir")));
        jMenuItemAyuda.setIcon(AvadsUtil.getImageIconByPath(AvadsMain.propC.getProperty("igu.principal.imagen.ayuda")));
        jMenuItemExaminarArchivo.setIcon(AvadsUtil.getImageIconByPath(AvadsMain.propC.getProperty("igu.principal.imagen.examinarArchivo")));
        jMenuItemConfiguracion.setIcon(AvadsUtil.getImageIconByPath(AvadsMain.propC.getProperty("igu.principal.imagen.configuracion")));
        jMenuItemEstadoArchivos.setIcon(AvadsUtil.getImageIconByPath(AvadsMain.propC.getProperty("igu.principal.imagen.estadoArchivos")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuAVADS = new javax.swing.JMenuBar();
        jMenuAcciones = new javax.swing.JMenu();
        jMenuItemExaminarArchivo = new javax.swing.JMenuItem();
        jMenuItemEstadoArchivos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuConfiguracion = new javax.swing.JMenu();
        jMenuItemConfiguracion = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItemAyuda = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));

        jMenuAcciones.setText("Acciones");

        jMenuItemExaminarArchivo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemExaminarArchivo.setText("jMenuItem1");
        jMenuItemExaminarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExaminarArchivoActionPerformed(evt);
            }
        });
        jMenuAcciones.add(jMenuItemExaminarArchivo);

        jMenuItemEstadoArchivos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemEstadoArchivos.setText("jMenuItem1");
        jMenuItemEstadoArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEstadoArchivosActionPerformed(evt);
            }
        });
        jMenuAcciones.add(jMenuItemEstadoArchivos);
        jMenuAcciones.add(jSeparator1);

        jMenuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSalir.setText("jMenuItem1");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuAcciones.add(jMenuItemSalir);

        jMenuAVADS.add(jMenuAcciones);

        jMenuConfiguracion.setText("Configuracion");

        jMenuItemConfiguracion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemConfiguracion.setText("jMenuItem1");
        jMenuItemConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConfiguracionActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jMenuItemConfiguracion);

        jMenuAVADS.add(jMenuConfiguracion);

        jMenuAyuda.setText("Ayuda");

        jMenuItemAyuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAyuda.setText("jMenuItem1");
        jMenuAyuda.add(jMenuItemAyuda);
        jMenuAyuda.add(jSeparator2);

        jMenuItemAcerca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAcerca.setText("jMenuItem1");
        jMenuAyuda.add(jMenuItemAcerca);

        jMenuAVADS.add(jMenuAyuda);

        setJMenuBar(jMenuAVADS);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed

        int resp = JOptionPane.showConfirmDialog(this, AvadsMain.propC.getProperty("principal.pregunta.salir"), AvadsMain.propC.getProperty("ventana.dialogo.atencion"), JOptionPane.YES_NO_OPTION);
        if(resp == JOptionPane.YES_OPTION)
        {
            AvadsMain.tray.remove(AvadsMain.trayIcon);
            AvadsMain.serviceDB.closeDB();
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConfiguracionActionPerformed

        
    }//GEN-LAST:event_jMenuItemConfiguracionActionPerformed

    private void jMenuItemExaminarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExaminarArchivoActionPerformed

    }//GEN-LAST:event_jMenuItemExaminarArchivoActionPerformed

    private void jMenuItemEstadoArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstadoArchivosActionPerformed

    }//GEN-LAST:event_jMenuItemEstadoArchivosActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuAVADS;
    private javax.swing.JMenu jMenuAcciones;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenu jMenuConfiguracion;
    private javax.swing.JMenuItem jMenuItemAcerca;
    private javax.swing.JMenuItem jMenuItemAyuda;
    private javax.swing.JMenuItem jMenuItemConfiguracion;
    private javax.swing.JMenuItem jMenuItemEstadoArchivos;
    private javax.swing.JMenuItem jMenuItemExaminarArchivo;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
